---
title: "Group project"
author: "Jingwen Liu"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(ggrepel)
```

## 

## Overall

```{r}

weather_station_folder <- "C:/Users/jingw/OneDrive/Desktop/EDA/Group Proj/Proj data/Weather Stations"

station_list <- list.dirs(weather_station_folder, recursive = FALSE, full.names = TRUE)

final_solar_dataset <- data.frame()

for (folder in station_list) {
  
  solar_file <- list.files(folder, pattern = "Solar Exposure.*Data.*\\.csv$", full.names = TRUE)
  
  if (length(solar_file) > 0) {
    
    all_data <- read_csv(solar_file)
    
    clean_data <- all_data %>%
      filter(Year >= 1995 & Year <= 2025) %>%
      select(Year, Month, Day, `Daily global solar exposure (MJ/m*m)`) %>% 
      mutate(Station = basename(folder))
    
    final_solar_dataset <- bind_rows(final_solar_dataset, clean_data)}}

view(final_solar_dataset)

```

```{r}

ggplot(final_solar_dataset, aes(x = as.factor(Year), y = `Daily global solar exposure (MJ/m*m)`, )) +
  geom_boxplot(fill = "red") +
  labs(title = "Solar Exposure in South Australia (1995 - 2005)", x = "Year", y = "Daily Global Solar Exposure (MJ/m^2)") +
  theme(panel.background = element_rect(fill = "white", colour = "white"),
    plot.background  = element_rect(fill = "white", colour = "white"),
    axis.text.x = element_text(angle = 90, vjust = 0.5), 
        axis.title.y = element_text(vjust = +3),         
        axis.title.x = element_text(vjust = -0.75))
  theme_minimal()



```

```{r}
ggplot(solar_stability, aes(x = Year, y = solar_iqr)) +
  geom_point() + 
  geom_line() +
  geom_smooth(method = "lm", color = "red",fill="pink", se = TRUE) +
  labs(x = "Year", y = "Spread (IQR) of Solar Exposure", title = "Trend of Annual Stability (Interquartile Range)") +
  theme_minimal()

```

```{r}
model_sd <- lm(solar_iqr ~ Year, data = solar_stability)
summary(model_sd)
```

```{r}
ggplot(solar_stability, aes(x = Year, y = solar_sd)) +
  geom_point() + 
  geom_line() +
  geom_smooth(method = "lm", color = "darkgreen",fill="lightgreen", se = TRUE) +
  labs(x = "Year", y = "Spread (Standard Diviation) of Solar Exposure", title = "Trend of Annual Variability (Standard Deviation)") +
  theme_minimal()
```

```{r}
model_sd <- lm(solar_sd ~ Year, data = solar_stability)
summary(model_sd)

```
